- id: weather
  alias: weather_report
  trigger:
  - at: 07:00:00
    platform: time
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度,百分之{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
- id: '1590392237688'
  alias: new
  description: ''
  trigger:
  - at: '15:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: camera.turn_on
- id: '1590397150531'
  alias: switch_hachina
  description: ''
  trigger:
  - at: '19:43:10'
    platform: time
  condition: []
  action:
  - data: {}
    service: hachina3.change_state
- id: '1590740963988'
  alias: com
  description: ''
  trigger:
  - entity_id: hachina2.hello_world
    from: 开
    platform: state
    to: 关
  - entity_id: hachina2.hello_world
    from: 关
    platform: state
    to: 开
  condition: []
  action:
  - data: {}
    service: hachina.change_state
