#map location
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  longitude: 121.61486
  latitude: 31.272674
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: Shanghai
  # Customization file
  customize: !include customize.yaml

zone:
  - name: School（LG）
    longitude: 121.898093
    latitude: 30.90808
    icon: mdi:school
    radius: 250
    
  - name: School(YP)
    longitude: 121.553436
    latitude: 31.278978
    icon: mdi:school
    radius: 250

#weather
sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - symbol
      - temperature        #气温
      - precipitation      #雨量
      - windSpeed          #风速
      - pressure           #气压
      - windDirection      #风向
      - humidity           #湿度
  

#ip camera
android_ip_webcam:
  - host: 192.168.1.102
    name: ip_webcam

#phone message
twilio:
  account_sid: AC01b235a8537b6e2fe09369f99f81f7b9
  auth_token: 77a1675f445f7d4681d1e8709f257140
  
notify:
  - name: my_twilio_sms
    platform: twilio_sms
    from_number: "+12058318736"
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
hachina:
#hachina1:
hachina2:
#hachina3:
#hachina5:
#  step: 5
#baidu say
tts:
#  - platform: google_translate
  - platform: baidu
    app_id: 19165941
    api_key: XUqFyxlgEllBGh5qqRMfTh4x
    secret_key: S6GPVANUOEH4NFYxyfkd9f3lQPXfkx3N
    language: zh
    #speed: 语速0~9
    #pitch: 语调0~9
    #volume: 音量0~15
    #person: 声音0~4  (0：女  1：男  3：百度合成  4：百度合成)
    person: 4


#kodi player
media_player:
  - platform: kodi
    host: 127.0.0.1
    port: 8081

#Camera
ffmpeg:
  ffmpeg_bin: 'D:\ffmpeg\bin\ffmpeg.exe'
  
camera:
  - platform: ffmpeg
    name: Cam01
    input: -f dshow -i video="Integrated Webcam"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
