- id: '1590135789386'
  alias: new
  description: ''
  trigger:
  - at: '16:25:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: camera.ip_webcam
    service: camera.turn_on
- alias: weather_report
  initial_state: true
  trigger:
  - platform: time_pattern
    hours: 17
    minutes: 50
    seconds: 0
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 20
  action:
  - service: tts.baidu_say
    data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃,湿度{{states('sensor.humidity')}},气压{{states('sensor.weather_pressure')}}
  id: f85b301b12644199b71838883aaf4743
- id: '1590477261766'
  alias: HaChina3
  description: ''
  trigger:
  - at: '15:18:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: hachina3.change_state
