homeassistant:
  # Name of the location where Home Assistant is running
  name: moocxingHome
  # Location required to calculate the time the sun rises and sets
  longitude: 109.83
  latitude: 40.65
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: Shanghai
  # Customization file
  customize: !include customize.yaml
zone:
  - name: school
    latitude: 31.278978
    longitude: 121.553436
    icon: mdi:school
    radius: 250

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
default_config:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

android_ip_webcam:
  - host: 192.168.43.1
    name: ip_webcam

tts:
  - platform: baidu
    app_id: 19165865
    api_key: W7N52MRGuGCyrrsm6aCRP4Y8
    secret_key: 8rzZd6FHqGnFPQloptdXGrHfLruy44QG
    language: zh
    person: 4

media_player:
  - platform: kodi
    host: 127.0.0.1
    port: 8081

twilio:
  account_sid: ACca6935750fab9f71108e81f538dc92a5
  auth_token: 51e815765eaebbbb84c760991b88a6e1
  
notify:
  - name: my_twilio_sms
    platform: twilio_sms
    from_number: "+12565888803"

#hachina:
#hachina2:
hachina3:

#hachina5:

#hachina10:

ffmpeg:
  ffmpeg_bin: 'E:\ffmpeg\bin\ffmpeg.exe'

camera:
  - platform: ffmpeg
    name: Cam01
    input: -f dshow -i video="HP Wide Vision HD Camera"