- id: '1590135787933'
  alias: new
  description: ''
  trigger:
  - at: '16:25:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: camer.ip_webcam
    service: automation.turn_on


- alias: weather_report
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 7
      minutes: 30
      seconds: 0
      
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 20  #判断气温是否高于20°C
        
  action:
    - service: tts.baidu_say
      data_template:
        entity_id: media_player.kodi
        message: "现在播报天气信息。温度，{{states('sensor.weather_temperature')}}°C, 湿度{{states('sensor.weather_humidity')}}，风速{{states('sensor.weather_wind_speed')}}, 气压{{states('sensor.weather_pressure')}}"
