- id: '1590135717799'
  alias: auto_test1
  description: 2020.5.22
  trigger:
  - at: '16:38'
    platform: time
  condition: []
  action:
  - service: camera.turn_on
- id: '1590741114526'
  alias: com_com
  description: ''
  trigger:
  - entity_id: hachina10.hello_world
    from: open
    platform: state
    to: close
  - entity_id: hachina10.hello_world
    from: close
    platform: state
    to: open
  condition: []
  action:
  - service: hachina10_2.change_state
- id: '1594007789351'
  alias: weather
  description: ''
  trigger:
  - at: '12:01'
    platform: time
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度，{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
